testes

diff --git a/.github/workflows/pipeline-v12.yml b/.github/workflows/pipeline-v12.yml
--- a/.github/workflows/pipeline-v12.yml
+++ b/.github/workflows/pipeline-v12.yml
@@ -2,9 +2,9 @@ name: Execução automação de testes
 
 on:
   pull_request:
-      types: [synchronize]
-      paths-ignore:
-        - '**.md'
+    types: [synchronize]
+    paths-ignore:
+      - '**.md'
   push:
     branches:
       - master
@@ -31,50 +31,49 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - run: npm install --verbose
-      
-     # Etapa de criação das pastas
+
+      # Etapa de criação das pastas
       - run: mkdir -p cypress/videos
       - run: mkdir -p cypress/screenshots
       - run: mkdir -p cypress/report
-    # Configuração da permissão
+
+      # Configuração da permissão
       - run: chmod -R a+w cypress/videos
       - run: chmod -R a+w cypress/screenshots
-      - run:  chmod -R a+w cypress/report
+      - run: chmod -R a+w cypress/report
+
       - name: Debug info
         run: |
           echo "PATH: $PATH"
           echo "Node.js version: $(node --version)"
           echo "npx version: $(npx --version)"
-          
+
       - name: Cypress run
         id: cypress_run
         run: |
-            npm run cypress:allure || exit 0
-            # Capture the exit code and set it as an output
-            # If Cypress run fails, it will still execute the subsequent steps
+          npm run cypress:allure || exit 0
+          # Capture the exit code and set it as an output
+          # If Cypress run fails, it will still execute the subsequent steps
         if: ${{ always() }}
         shell: bash  
-        #  run: npm run cypress:allure 
-          # command: npx cypress run --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
-        #  command: npm run ${{github.event.inputs.teste || env.DEFAULT_TESTE}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
-      
+      #  run: npm run cypress:allure 
+        # command: npx cypress run --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
+      #  command: npm run ${{github.event.inputs.teste || env.DEFAULT_TESTE}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}}
+    
+
       - name: Get Allure History
         uses: actions/checkout@v2
-        if: always()
         with:
           ref: gh-pages
-          path: gh-pages
-      
-      - name: Generate Allure Report
-        uses: simple-elf/allure-report-action@master
-        if: always()
-        with:
-          allure_results: allure-results
-          allure_history: allure-history
-          keep_reports: 20
-      
+          path: allure-history
+
+      - name: Copy Allure report artifacts
+        run: |
+          mkdir -p allure-history
+          cp -r allure-results allure-history/results
+          cp -r allure-report allure-history/report
+
       - name: Deploy report to Github Pages
-        if: always()
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -86,7 +85,7 @@ jobs:
           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
           PUBLISH_BRANCH: gh-pages
           PUBLISH_DIR: allure-history
-      
+
       - name: Enviar notificação Slack - Sucesso
         if: ${{ success() }}
         uses: rtCamp/action-slack-notify@v2
@@ -97,7 +96,7 @@ jobs:
           SLACK_MESSAGE: 'Sucesso na execução de testes do PR :white_check_mark:'
           SLACK_TITlE: 'Sucesso na execução de testes do PR :white_check_mark:'
           SLACK_USERNAME: SUCESS0
-      
+
       - name: Enviar notificação Slack - Falha
         if: ${{ failure() }}
         uses: rtCamp/action-slack-notify@v2
@@ -108,4 +107,3 @@ jobs:
           SLACK_MESSAGE: 'Falha na execução de testes do PR :fire:'
           SLACK_TITlE: 'Falha na execução de testes do PR :fire:'
           SLACK_USERNAME: FALHA
-      
